const ua = {
  "code": "ua",
  "home": "Головна",
  "help": "Допомога",
  "title": "Своя Гра",
  "bundle": "Створити низку питань",
  "play": "Почати гру",
  "name": {
    "placeholder": "Введіть Ваше ім'я",
    "title": "Може мати тільки цифри та літери"
  },
  "help-page": "Допомога",
  "new-game": "Нова Гра",
  "title-word": "Назва",
  "password-word": "Пароль",
  "question-bundle-word": "Низка питань",
  "random-word": "Випадковий",
  "download-word": "Завантажити",
  "game-type-word": "Тип гри",
  "simple-word": "Проста",
  "classic-word": "Класична",
  "role-word": "Роль",
  "player-word": "Гравець",
  "findBundleByName-word": "Знайти низку питань за ім'ям",
  "game-master-word": "Ведучий",
  "players-word": "Гравці",
  "total-word": "Всього",
  "people-word": "Люди",
  "settings": "Налаштування",
  "create-game": "Створити нову гру",
  "join-lobby": "Увійти до лоббі",
  "pack-title-word": "Назва низки питань",
  "author-word": "Автор",
  "language": "Мова",
  "german": "Німецька",
  "ukrainian": "Українська",
  "mode": "Мод",
  "round": "Раунд",
  "final-round": "Фінальний Раунд",
  "question": "Питання",
  "regular": "Звичайне питання",
  "bet": "Питання зі ставкою",
  "secret": "Питання з секретом",
  "final": "Фінальне питання",
  "sponsored": "Питання без ризику",
  'invalid': "Неприйнятні дані на питанні",
  "points": "балів",
  "category": "Категорія",
  "category-name": "Назва Категорії",
  "question-type": {
    "placeholder": "Тип запитання"
  },
  "input-question": {
    "placeholder": "Питання"
  },
  "input-image": "Оберіть картинку для питання",
  "input-audio": "Оберіть аудіофайл для питання",
  "optional": "Опціонально",
  "sep-answers": "Відділяйте правильні і неправильні варіанти комами",
  "answers": {
    "placeholder": "Відповіді"
  },
  "wrong-answers-input": {
    "placeholder": "Неправильні відповіді(необов'язково)"
  },
  "input-category": {
    "placeholder": "Категорія"
  },
  "owner": "Власник",
  "game-master": "Ведучий",
  "join": "Приєднатися",
  "change-sums": "Змінити бали",
  "report": "Поскаржитись",
  "pause": "Пауза",
  "continue": "Продовжити",
  "exit": "Вихід",
  "rules": "Правила",
  "questions": "Питання",
  "bugs": "Баги",
  "rules-of-the-game": "Правила гри",
  "how-to-bundle": "Як створити мої власні питання?",
  "how-to-bundle-1": "На головній сторінці натисніть 'Створити низку питань'",
  "how-to-bundle-2": "Заповніть усі порожні поля в формі і натисніть 'Створити низку питань'",
  "how-to-bundle-3": "Завантажте низку питань в форматі JSON. До того ж опціонально можна зберегти низку в нашій базі даних",
  "found-bug": "Знайшли баг?",
  "rules-text": "Теж саме, тільки українською",
  "bug-handling-text": "Теж саме, тільки українською",
  "save-to-db": "Додати низку питань в базу даних",
  "correct-answers": "Правильні відповіді",
  "wrong-answers": "Неправильні відповіді",
  "correct": "Правильно",
  "wrong": "Неправильно",
  "onleave": "Ви дійсно хочете залишити цю гру?",
  "find-games": {
    "placeholder": "Знайди свою гру!",
  },
  "players-online": "Гравців онлайн: ",
  "nopass": "Без пароля",
  "pass": "З паролем",
  "all-games": "Всі ігри",
  "game-running": "Гра вже почалась",
  "username-taken": "В цій грі вже є гравець з Вашим нікнеймом. Чи не хотіли б Ви змінити ім'я?",
  "start-min": "Необхідно мінімум 3 гравці, щоб почати гру.",
  "yes": "Так",
  "no": "Ні",
  "apply": "Примінити",
  "agree": "Погодитись",
  "disagree": "Не погодитись",
  "make-bet": "Будь ласка, введіть Вашу ставку",
  "choose-person-to-answer": " обирає, хто відповідатиме на запитання.",
  "gamemaster-checks-answers": "Ведучий перевіряє правильність відповіді.",
  "appeal": "Фаза апеляції.",
  "appeal-approved": "Апеляція схвалена!",
  "appeal-denied": "Апеляція відхилена!",
  "someone's-move": " ходить.",
  "count-players-1": "гравців,",
  "count-players-2": "щоб почати гру",
  "prime-meridian": "час (нульовий меридіан) додається до назви",
  "secret-question": "Секретне питання",
  "bet-question": "Питання зі ставкою",
}

export { ua };
